project:
  type: website
  render:
    - "*.qmd"
    - "!tmp/"

website:
  title: "Emma Tye"
  navbar:
    background: secondary
    search: true
    left:
      - presentations/index.qmd
      - papers/index.qmd
  page-footer:
    left:
      - icon: github
        href: https://github.com/EmmaTye
      - icon: linkedin
        href: https://www.linkedin.com/in/emma-tye/
      - text: personal email
        href: mailto:tyelouiseemma@gmail.com
      - text: work email
        href: mailto:emma.tye@strath.ac.uk

format:
  html:
    theme:
      - minty
      - brand
    css: styles.css
    toc: true

execute:
  freeze: auto

